title: Yves Nsoga # your name (or website title) here
logo: "/images/IMG-6762.jpg?raw=true" #your photo (or logo) here
description: >  # your text below (remove <br> elements if you don't need line breaks)
  <br> Ph.D. student in Biomedical  engineering </br>
  <br> Machine Learning engineer || </br>
  <br> Machine learning, Healthcare, Cybersecurity</br>
  <br><br>
  <a href="https://www.linkedin.com/in/yves-nsoga-pro-link/"> View My Linkedin Profile </a> 
theme: jekyll-theme-minimal #jekyll-theme-cayman 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
