title: Yves Nsoga # your name (or website title) here
logo: "/images/IMG-6762.jpg?raw=true" #your photo (or logo) here
description: >  # your text below (remove <br> elements if you don't need line breaks)
  <br> Machine learning, Health care, Cybersecurity, Sciences </br>
theme: jekyll-theme-minimal #jekyll-theme-cayman 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
